In libiconv, remove `genflags.c` from the CMake configuration.
It caused compilation errors in MSVC:

```
D:\LyX\lyx\3rdparty\libiconv\1.18\lib\genflags.c(37): error C2016: C requires that a struct or union have at least one member
D:\LyX\lyx\3rdparty\libiconv\1.18\lib\genflags.c(38): error C2016: C requires that a struct or union have at least one member
D:\LyX\lyx\3rdparty\libiconv\1.18\lib\genflags.c(39): error C2016: C requires that a struct or union have at least one member
```